package com.example.data.model

import androidx.room.Entity
import androidx.room.PrimaryKey
import java.io.Serializable

// Candle representing open, high, low, close data
data class Candle(
    val open: Double,
    val high: Double,
    val low: Double,
    val close: Double,
    val volume: Double = 0.0,
    val timestamp: Long
) : Serializable

// Watchlist item representing tracked symbols in local DB
@Entity(tableName = "watchlist_items")
data class WatchlistItem(
    @PrimaryKey val symbol: String,
    val name: String,
    val type: String, // CRYPTO, STOCK, FOREX, INDEX, COMMODITY
    val price: Double = 0.0,
    val change: Double = 0.0,
    val addedAt: Long = System.currentTimeMillis()
) : Serializable

// Price alert entity saved by users
@Entity(tableName = "price_alerts")
data class PriceAlert(
    @PrimaryKey(autoGenerate = true) val id: Int = 0,
    val symbol: String,
    val targetPrice: Double,
    val condition: String, // ABOVE, BELOW
    val isActive: Boolean = true,
    val createdAt: Long = System.currentTimeMillis()
) : Serializable

// Historical and current scalp signals generated by local engine
@Entity(tableName = "scalp_signals")
data class ScalpSignal(
    @PrimaryKey(autoGenerate = true) val id: Int = 0,
    val symbol: String,
    val name: String,
    val direction: String, // BUY, SELL
    val timeframe: String, // 1m, 5m, 15m
    val entryPrice: Double,
    val takeProfit: Double,
    val stopLoss: Double,
    val confidence: Double, // 0 - 1.0 (or 0 - 100%)
    val triggerIndication: String, // "EMA cross + RSI"
    val timestamp: Long = System.currentTimeMillis(),
    val status: String = "OPEN" // OPEN, WIN, LOSS
) : Serializable

// Single message in the AI chat history
@Entity(tableName = "chat_messages")
data class ChatMessage(
    @PrimaryKey(autoGenerate = true) val id: Int = 0,
    val sender: String, // USER, AI
    val content: String,
    val timestamp: Long = System.currentTimeMillis()
) : Serializable

// API keys setup for multi-key rotation and manual setup
@Entity(tableName = "api_keys")
data class ApiKeyInfo(
    @PrimaryKey val keyType: String, // OPENROUTER, FINNHUB, TWELVEDATA, NEWSAPI
    val apiKeyValue: String,
    val lastUsed: Long = 0,
    val isLimitReached: Boolean = false,
    val requestCount: Int = 0
) : Serializable
